In [1]:
import numpy as np

### Creating np arrays

In [9]:
arr = np.array([1,2,3,4,5]) #Creating a simple numpy array

In [10]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr2 =np.arange(1,10,1) #Creating an array of numbers 1 to (10 - 1) with iteof +1

In [12]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3 = np.linspace(1, 10, 4) # creating an array of 4 number which a equally spreaded in numbers 1 to 10

In [20]:
arr3

array([ 1.,  4.,  7., 10.])

In [21]:
np.zeros((3,5)) # zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,4)) # ones`

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Array properties

In [24]:
arr.ndim #dimensions

1

In [25]:
arr4 = np.array([[2,3],[4,5]])

In [26]:
arr4

array([[2, 3],
       [4, 5]])

In [29]:
arr4.ndim # 2 dimensions

2

In [31]:
arr4.shape # shape of an array

(2, 2)

In [33]:
arr4.size #Total numbers of elements in an array

4

In [34]:
arr4.dtype # datatype

dtype('int64')

## Slicing and Indexing

In [35]:
arr[2] #basic indexing

np.int64(3)

In [37]:
arr[2:4] #slicing

array([3, 4])

In [41]:
arr4

array([[2, 3],
       [4, 5]])

In [40]:
arr4[1,0] #2D slicing

np.int64(4)

## Reshaping Arrays

In [42]:
arr5 =np.arange(8)

In [43]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
arr5.reshape(2,4) # Reshaping

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
arr5.flatten() #Multi Dimension array into 1D array 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
arr5.ravel() #only view as 1D

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
arr6 = arr5.reshape(2,4)

In [50]:
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr6.T #Transpose

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])