In [1]:
import numpy as np

### Creating np arrays

In [9]:
arr = np.array([1,2,3,4,5]) #Creating a simple numpy array

In [10]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr2 =np.arange(1,10,1) #Creating an array of numbers 1 to (10 - 1) with iteof +1

In [12]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3 = np.linspace(1, 10, 4) # creating an array of 4 number which a equally spreaded in numbers 1 to 10

In [20]:
arr3

array([ 1.,  4.,  7., 10.])

In [21]:
np.zeros((3,5)) # zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,4)) # ones`

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Array properties

In [24]:
arr.ndim #dimensions

1

In [25]:
arr4 = np.array([[2,3],[4,5]])

In [26]:
arr4

array([[2, 3],
       [4, 5]])

In [29]:
arr4.ndim # 2 dimensions

2

In [31]:
arr4.shape # shape of an array

(2, 2)

In [33]:
arr4.size #Total numbers of elements in an array

4

In [34]:
arr4.dtype # datatype

dtype('int64')