In [1]:
import numpy as np

### Creating np arrays

In [9]:
arr = np.array([1,2,3,4,5]) #Creating a simple numpy array

In [10]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr2 =np.arange(1,10,1) #Creating an array of numbers 1 to (10 - 1) with iteof +1

In [12]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3 = np.linspace(1, 10, 4) # creating an array of 4 number which a equally spreaded in numbers 1 to 10

In [20]:
arr3

array([ 1.,  4.,  7., 10.])

In [97]:
np.zeros((3,5)) # zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,4)) # ones`

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Array properties

In [24]:
arr.ndim #dimensions

1

In [25]:
arr4 = np.array([[2,3],[4,5]])

In [26]:
arr4

array([[2, 3],
       [4, 5]])

In [29]:
arr4.ndim # 2 dimensions

2

In [31]:
arr4.shape # shape of an array

(2, 2)

In [33]:
arr4.size #Total numbers of elements in an array

4

In [34]:
arr4.dtype # datatype

dtype('int64')

## Slicing and Indexing

In [35]:
arr[2] #basic indexing

np.int64(3)

In [37]:
arr[2:4] #slicing

array([3, 4])

In [41]:
arr4

array([[2, 3],
       [4, 5]])

In [40]:
arr4[1,0] #2D slicing

np.int64(4)

## Reshaping Arrays

In [42]:
arr5 =np.arange(8)

In [43]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
arr5.reshape(2,4) # Reshaping

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
arr5.flatten() #Multi Dimension array into 1D array 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
arr5.ravel() #only view as 1D

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
arr6 = arr5.reshape(2,4)

In [50]:
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr6.T #Transpose

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

## Joining and Splitting Arrays

In [55]:
np.concatenate([arr,arr2]) #Concatenation of two arrays(same ndims)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr6 = np.array([[6,7],[8,9]])

In [64]:
np.vstack((arr4,arr6)) #vertical stacking

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
np.hstack((arr4,arr6)) #horizontal stacking

array([[2, 3, 6, 7],
       [4, 5, 8, 9]])

In [70]:
np.split(arr4,2) #splitting an array into two or more equal partrs

[array([[2, 3]]), array([[4, 5]])]

## Mathematical Opertaions

In [72]:
arr7 =np.array([1,3,4,6])

In [73]:
arr8 = np.array([4,6,8,9])

In [75]:
arr7 + arr8 #Addition

array([ 5,  9, 12, 15])

In [77]:
arr7 - arr8 # Substraction

array([-3, -3, -4, -3])

In [79]:
arr7 * arr8# Multiplication

array([ 4, 18, 32, 54])

In [80]:
arr7  / arr8 # Division

array([0.25      , 0.5       , 0.5       , 0.66666667])

## Braodcasting - Very Important
Allows operations between arrays of different shapes

In [82]:
a = np.array([1,3,5])
b = np.array([[24],[56]])
a + b

array([[25, 27, 29],
       [57, 59, 61]])

In [83]:
a - b

array([[-23, -21, -19],
       [-55, -53, -51]])

In [84]:
a * b

array([[ 24,  72, 120],
       [ 56, 168, 280]])

In [85]:
a / b

array([[0.04166667, 0.125     , 0.20833333],
       [0.01785714, 0.05357143, 0.08928571]])

## Boolean Operations & Filtering

In [86]:
#Comparison
a > 2

array([False,  True,  True])

In [87]:
# Boolean Indexing
a[a > 2]

array([3, 5])

In [90]:
# where(condition, If true do this, else do this)
np.where(a>2, 5, 0) 

array([0, 5, 5])

## Sorting And Searching

In [92]:
np.sort(arr) #Sorting

array([1, 2, 3, 4, 5])

In [93]:
np.argsort(arr) # return indices that would sort an array

array([0, 1, 2, 3, 4])

In [94]:
np.argmax(arr) # max value of indices

np.int64(4)

In [96]:
np.argmin(arr) # min value of indices

np.int64(0)

## Random Numbers

In [100]:
np.random.rand(2,4) # Array of random numbers

array([[0.12376419, 0.99164817, 0.81872541, 0.39210304],
       [0.36910861, 0.15854346, 0.34885114, 0.03710907]])

In [101]:
np.random.randn(2,3)

array([[-0.71564106,  1.470981  ,  1.11608887],
       [ 0.66845456,  0.18500489, -1.16486785]])

In [103]:
np.random.randint(1, 10, size = 5) # Array of random 5 integer numbers

array([4, 9, 4, 6, 3], dtype=int32)

In [112]:
np.random.seed(42) # Reproduciblity - used to make random numbers reproducible.

## Linear Algebra

In [118]:
c = np.array([[2,3],[4,5]])
d = np.array([[5,6],[6,7]])
np.dot(c,d)  # Dot product

array([[28, 33],
       [50, 59]])

In [121]:
c@d # Dot product

array([[28, 33],
       [50, 59]])

In [154]:
np.matmul(c,d) # Dot product

array([[28, 33],
       [50, 59]])

In [126]:
#inverse
np.linalg.inv(c)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [130]:
# Determinant
np.linalg.det(c)

np.float64(-2.0)

## Stastistical Functions

In [136]:
np.percentile(a,50) #Percentile

np.float64(3.0)

In [138]:
np.median(a) #Median

np.float64(3.0)

In [139]:
np.mean(a) #Mean

np.float64(3.0)

In [142]:
np.corrcoef(c,d) # Correlation coefficient

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Missing Values

In [144]:
np.isnan(c) #NaN Handling

array([[False, False],
       [False, False]])

In [146]:
np.nanmean(c) #NaN mean

np.float64(3.5)

## Copy VS View

In [148]:
b = a.copy()

In [149]:
b

array([1, 3, 5])

In [155]:
a = arr.view() # View Behavior

In [156]:
a

array([1, 2, 3, 4, 5])

## Speciality of NumPy (Why it’s powerful)
1. Super fast numerical operations.
2. Multidimensional arrays (ndarray).
3. Vectorization (no loops needed).
4. Powerful mathematical functions.
5. Memory efficient.
6. Foundation of Data Science stack.
7. Random data generation.