In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
n_arr = np.arange(2, 31, 2)
print(n_arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [4]:
reshaped = n_arr.reshape((3, 5))
print(reshaped)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [5]:
flatten = reshaped.flatten()
print(flatten)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [6]:
raveled = n_arr.ravel()
print(raveled)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [7]:
trans = reshaped.T
print(trans)

[[ 2 12 22]
 [ 4 14 24]
 [ 6 16 26]
 [ 8 18 28]
 [10 20 30]]


In [8]:
num_arr = np.full((3,5), 8)
print(num_arr)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [9]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
print(arr.shape)


(2, 3)


In [12]:
print(arr.ndim)

2


In [13]:
print(arr.size)

6


In [14]:
print(arr.dtype)

int64


In [15]:
arr26 = np.array([2,5,9,3,7,5,6,7])
arr26

array([2, 5, 9, 3, 7, 5, 6, 7])

In [18]:
new_arr26 = arr26 **2
new_arr26

array([ 4, 25, 81,  9, 49, 25, 36, 49])

In [20]:
np.sort(new_arr26)

array([ 4,  9, 25, 25, 36, 49, 49, 81])

In [25]:
mask = new_arr26 = new_arr26
print("No same nums", new_arr26[mask])

No same nums [ 4 25 81  9 49 25 36 49]
